### PR TITLE
Add CI/CD

### LINKED ISSUE #19: HTTPS hosting
We need to have static file hosting on a HTTPS domain. Note that an SSL certificate is required for a WPA with the features that we need (plus it's the norm).

Let's Encrypt should suffice but any other means of getting a valid certificate is fine right now.

### PR DESCRIPTION
**Pull request by 1aziz**
To optimize our delivery by automating deployments to the development and production environments on App Engine.

Every update on any branch will go to development while merging to develop runs steps to deploy to production. Developers can quickly check their _tested and locally-working_ functionalities and master remains untouched as the single source of truth.

Updated endpoints:

https://dev-dot-acn-liquid-studio-nl.appspot.com/
https://acn-liquid-studio-nl.appspot.com/

### CODE REVIEW

**Comment by 1aziz** [comment]
Needs work.

**Comment by basdp** [comment]
The target url of the dev deploy task shows ***. Do you know why that is? Is it trying to supress a secret variable that we set to the same as the subdomain name or something?

**Comment by basdp** [comment]
I get this error in chrome on the dev domain:
NET::ERR_CERT_COMMON_NAME_INVALID

Don't get it on the https://acn-liquid-studio-nl.appspot.com/ one.

**Comment by 1aziz** [comment]
> The target url of the dev deploy task shows ***. Do you know why that is? Is it trying to supress a secret variable that we set to the same as the subdomain name or something?

They get hidden, indeed. The project name (which is by default the app name) is injected as a secret, that could be the reason why GitLab is now showing that. I tried to add the `application` parameter, but it seems to be deprecated.

**Comment by 1aziz** [comment]
> I get this error in chrome on the dev domain:
> NET::ERR_CERT_COMMON_NAME_INVALID
> 
> Don't get it on the https://acn-liquid-studio-nl.appspot.com/ one.

It seems a certificate was previously configured with that URL, if that's the case, there would be no need for requesting a new one! but configuring it with the sub-domain(s)?
I'm gonna take a look.

**Comment by basdp** [comment]
> > The target url of the dev deploy task shows ***. Do you know why that is? Is it trying to supress a secret variable that we set to the same as the subdomain name or something?
> 
> They get hidden, indeed. The project name (which is by default the app name) is injected as a secret, that could be the reason why GitLab is now showing that. I tried to add the `application` parameter, but it seems to be deprecated.

yeah that's it. If it's injected as a secret, it will be hidden. Not a huge problem.

**Review by basdp — CHANGES_REQUESTED** [review]
Approved if we can fix the ssl errors (looks like iPhone and Chrome won't allow to ignore them).

**Comment by 1aziz** [comment]
> Approved if we can fix the ssl errors (looks like iPhone and Chrome won't allow to ignore them).

Okay, so this is the link to prod: https://acn-liquid-studio-nl.appspot.com/

And dev is here: https://dev-dot-acn-liquid-studio-nl.appspot.com/

**Review by basdp — CHANGES_REQUESTED** [review]
There seems to be an issue when the pipeline runs. It is triggered both by a `push` and a `pull_request`, and thus 2 deployments run in parallel, which breaks the system.

```
ERROR: (gcloud.app.deploy) ABORTED: Cannot operate on apps/***/services/default/versions/dev because an operation is already in progress for apps/***/services/default/versions/dev by f0ba963c-801e-47da-9c22-055843f76cf2.
```

**Comment by 1aziz** [comment]
> There seems to be an issue when the pipeline runs. It is triggered both by a `push` and a `pull_request`, and thus 2 deployments run in parallel, which breaks the system.
> 
> ```
> ERROR: (gcloud.app.deploy) ABORTED: Cannot operate on apps/***/services/default/versions/dev because an operation is already in progress for apps/***/services/default/versions/dev by f0ba963c-801e-47da-9c22-055843f76cf2.
> ```

It's now solved, after updating the branch no additional pipeline started.

**Review by basdp — APPROVED** [review]

**Review by guillertal — APPROVED** [review]

**Pull request merged**
